### ISSUE TITLE
ocsm tun failed to install

### ISSUE THREAD

**Issue by malikshi** [helmiau/HelmiWrt-OS#41]
```sh
  Configuring permissions....

chmod: /etc/openclash/core/clash*: No such file or directory

  Starting Clash....


===============================
```

just flash and doing ocsm install TUN and install premium

**Comment by rootjack404** [comment]
Need more details. Those error log is just stating that there were no files named clash*. If it's failed to install please provide the error message while installing/downloading the tun or premium.

**Comment by rootjack404** [comment]
I'm just take a look at the ocsm script file, and it seems the script was failed to move the downloaded files for tun or any other that extracted without named "clash".
```
function helmi_install_tun() {
	if [[ -s /root/clash-$ARCH$ORIEXT ]]; then
		echo -e "${G}"
		tar xzf /root/clash-$ARCH$ORIEXT -C /root/
		mv /root/clash $TUN //HERE
		rm -f /root/clash-$ARCH$ORIEXT || true
		echo "  TUN Core Install Done...."
	else
		echo -e "${R}"
		echo "  TUN Core Install Failed...."
		echo -e "${G}"
	fi
}
```
since the downloaded file were using gunzip so the filename that extracted is the same as the downloaded archive file if it were extracted and those command wasn't the correct one to extract a gunzip files which supposed to be `gunzip filename`. And seems like the install tun download function were using $ORIEXT which lead to .tar.gz were the actual file extension in the API is .gz, you can check here https://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN-Premium.

Would like to hear if its fixed the problem or not, since i am too lazy to try it by myself.

**Comment by malikshi** [comment]
> @rootjack404 
Would like to hear if its fixed the problem or not, since i am too lazy to try it by myself.

Yup yup, can you sent PR?
